android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---java.util.Calendar: getInstance()java.util.Calendar : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---android.util.Log: i(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer---android.util.Log: i(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---java.util.Calendar: get(java.lang.Integer)java.lang.Integer : 0.0
java.util.Calendar: get(java.lang.Integer)java.lang.Integer---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: i(java.lang.String,java.lang.String)java.lang.Integer---java.util.Calendar: getInstance()java.util.Calendar : 0.0
java.util.Calendar: get(java.lang.Integer)java.lang.Integer---java.util.Calendar: getInstance()java.util.Calendar : 0.0
android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer---java.util.Calendar: getInstance()java.util.Calendar : 0.0
java.util.Calendar: get(java.lang.Integer)java.lang.Integer---android.util.Log: i(java.lang.String,java.lang.String)java.lang.Integer : 0.0
