android.net.NetworkInfo: getType()java.lang.Integer---android.net.NetworkInfo: getState()android.net.NetworkInfo$State : 0.0
android.net.NetworkInfo: getState()android.net.NetworkInfo$State---android.util.Log: i(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.util.Log: i(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: v(java.lang.String,java.lang.String)java.lang.Integer---android.util.Log: i(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: w(java.lang.String,java.lang.String)java.lang.Integer---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo---android.util.Log: i(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: v(java.lang.String,java.lang.String)java.lang.Integer---android.util.Log: w(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.net.NetworkInfo: getState()android.net.NetworkInfo$State---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.util.Log: w(java.lang.String,java.lang.String)java.lang.Integer---android.net.NetworkInfo: getState()android.net.NetworkInfo$State : 0.0
android.util.Log: v(java.lang.String,java.lang.String)java.lang.Integer---android.net.NetworkInfo: getType()java.lang.Integer : 0.0
android.util.Log: w(java.lang.String,java.lang.String)java.lang.Integer---android.util.Log: i(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: v(java.lang.String,java.lang.String)java.lang.Integer---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.util.Log: w(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: v(java.lang.String,java.lang.String)java.lang.Integer---android.net.NetworkInfo: getState()android.net.NetworkInfo$State : 0.0
