android.net.NetworkInfo: getExtraInfo()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.net.NetworkInfo: getTypeName()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo---android.net.NetworkInfo: getTypeName()java.lang.String : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getLine1Number()java.lang.String---android.net.NetworkInfo: getTypeName()java.lang.String : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.net.NetworkInfo: getTypeName()java.lang.String : 0.0
