java.io.FileOutputStream: write([BII)void---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---java.io.FileOutputStream: write([BII)void : 0.0
java.io.FileOutputStream: write([BII)void---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
java.io.FileOutputStream: write([B)void---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---java.io.FileOutputStream: write([B)void : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---java.net.URL: openConnection()java.net.URLConnection : 0.0
java.io.FileOutputStream: write([BII)void---java.io.FileOutputStream: write([B)void : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---java.io.FileOutputStream: write([B)void : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
