android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getSimOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getLine1Number()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperator()java.lang.String---android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String---android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getSimOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getSimOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperator()java.lang.String---android.telephony.TelephonyManager: getPhoneType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimState()java.lang.Integer---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkOperator()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getSimOperatorName()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperator()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getPhoneType()java.lang.Integer---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getLine1Number()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimState()java.lang.Integer---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getPhoneType()java.lang.Integer---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperator()java.lang.String---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getPhoneType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getPhoneType()java.lang.Integer---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getPhoneType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimOperator()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getPhoneType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String---android.telephony.TelephonyManager: getPhoneType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getPhoneType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getSubscriberId()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkOperator()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperator()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getSimOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkOperator()java.lang.String---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getPhoneType()java.lang.Integer---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getPhoneType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getSimOperatorName()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimState()java.lang.Integer---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getSimState()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getSimOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimCountryIso()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperator()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperator()java.lang.String---android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getLine1Number()java.lang.String : 0.0
android.telephony.TelephonyManager: getPhoneType()java.lang.Integer---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperator()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkCountryIso()java.lang.String---android.telephony.TelephonyManager: getPhoneType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getNetworkOperator()java.lang.String---android.telephony.TelephonyManager: getNetworkType()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getNetworkOperatorName()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimOperatorName()java.lang.String---android.telephony.TelephonyManager: getDeviceSoftwareVersion()java.lang.String : 0.0
android.telephony.TelephonyManager: getVoiceMailNumber()java.lang.String---android.telephony.TelephonyManager: getPhoneType()java.lang.Integer : 0.0
