android.net.NetworkInfo: getType()java.lang.Integer---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.net.NetworkInfo: getExtraInfo()java.lang.String : 0.0
android.location.Location: getLongitude()D---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer---android.location.Location: getAccuracy()F : 0.0
android.location.Location: getLongitude()D---android.location.Location: getTime()J : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo---android.location.Location: getLatitude()D : 0.0
android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.telephony.TelephonyManager: getNetworkOperator()java.lang.String---android.location.Location: getLatitude()D : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection---android.location.Location: getAccuracy()F : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---android.location.Location: getAccuracy()F : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer : 0.0
android.location.Location: getLongitude()D---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.location.Location: getLatitude()D : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.location.Location: getAccuracy()F : 0.0
android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.net.NetworkInfo: getType()java.lang.Integer : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer---android.location.Location: getAccuracy()F : 0.0
android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.telephony.TelephonyManager: getSubscriberId()java.lang.String : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.location.Location: getLatitude()D : 0.0
android.location.Location: getLongitude()D---android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String : 0.0
android.location.Location: getTime()J---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation---android.location.Location: getLatitude()D : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.location.Location: getLongitude()D : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.location.Location: getAccuracy()F : 0.0
android.location.Location: getLongitude()D---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.location.Location: getTime()J : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer : 0.0
android.location.Location: getTime()J---android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer : 0.0
java.net.URL: openConnection()java.net.URLConnection---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.location.Location: getLongitude()D---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.location.Location: getLatitude()D : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.location.Location: getAccuracy()F : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation---android.location.Location: getAccuracy()F : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.net.NetworkInfo: getType()java.lang.Integer : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.net.NetworkInfo: getType()java.lang.Integer : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String : 0.0
android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer---android.location.Location: getLatitude()D : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.location.Location: getTime()J : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer : 0.0
android.location.Location: getLongitude()D---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.location.Location: getTime()J : 0.0
android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.location.Location: getTime()J : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location : 0.0
android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
java.net.URL: openConnection()java.net.URLConnection---android.location.Location: getLatitude()D : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.location.Location: getLatitude()D : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.location.Location: getTime()J : 0.0
android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer---android.location.Location: getLatitude()D : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.location.Location: getTime()J---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.location.Location: getTime()J : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location : 0.0
android.location.Location: getLongitude()D---android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String : 0.0
android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo---android.location.Location: getAccuracy()F : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String : 0.0
android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
java.net.URL: openConnection()java.net.URLConnection---android.location.Location: getAccuracy()F : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.location.Location: getTime()J---java.net.URL: openConnection()java.net.URLConnection : 0.0
java.net.URL: openConnection()java.net.URLConnection---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer : 0.0
android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.location.Location: getLongitude()D---android.location.Location: getLatitude()D : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.location.Location: getAccuracy()F : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.location.Location: getLongitude()D : 0.0
android.location.Location: getLongitude()D---android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer : 0.0
android.location.Location: getAccuracy()F---android.location.Location: getLatitude()D : 0.0
java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection---android.location.Location: getLatitude()D : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.location.Location: getLongitude()D---android.net.NetworkInfo: getType()java.lang.Integer : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.location.Location: getLatitude()D : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.location.Location: getTime()J : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.location.Location: getLongitude()D : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
java.net.URL: openConnection()java.net.URLConnection---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.location.Location: getLongitude()D---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.location.Location: getAccuracy()F : 0.0
android.location.Location: getLongitude()D---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.net.NetworkInfo: getType()java.lang.Integer : 0.0
android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.location.Location: getTime()J---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.net.NetworkInfo: getType()java.lang.Integer : 0.0
java.net.URL: openConnection()java.net.URLConnection---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.location.Location: getTime()J---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.telephony.TelephonyManager: getNetworkOperator()java.lang.String---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.location.Location: getAccuracy()F : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.location.Location: getLongitude()D---android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer : 0.0
android.location.Location: getTime()J---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.location.Location: getLongitude()D : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.location.Location: getAccuracy()F : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.location.Location: getAccuracy()F : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.location.Location: getLongitude()D---android.location.Location: getAccuracy()F : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer : 0.0
android.location.Location: getTime()J---android.location.Location: getLatitude()D : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer : 0.0
android.telephony.TelephonyManager: getDeviceId()java.lang.String---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.telephony.TelephonyManager: getSimSerialNumber()java.lang.String---android.location.Location: getLatitude()D : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---java.net.URL: openConnection(java.net.Proxy)java.net.URLConnection : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.util.Log: e(java.lang.String,java.lang.String)java.lang.Integer---android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation : 0.0
android.net.NetworkInfo: getExtraInfo()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer---android.location.Location: getLatitude()D : 0.0
android.telephony.TelephonyManager: getNetworkOperator()java.lang.String---android.location.Location: getAccuracy()F : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.location.Location: getLatitude()D : 0.0
android.location.Location: getTime()J---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.location.Location: getTime()J---android.location.Location: getAccuracy()F : 0.0
android.net.NetworkInfo: getType()java.lang.Integer---android.telephony.TelephonyManager: getDeviceId()java.lang.String : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.net.NetworkInfo: getExtraInfo()java.lang.String : 0.0
android.location.LocationManager: getLastKnownLocation(java.lang.String)android.location.Location---android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer : 0.0
android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer---java.net.URL: openConnection()java.net.URLConnection : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.location.Location: getLatitude()D : 0.0
android.telephony.TelephonyManager: getSubscriberId()java.lang.String---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.gsm.GsmCellLocation: getCid()java.lang.Integer---android.net.NetworkInfo: getType()java.lang.Integer : 0.0
android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.gsm.GsmCellLocation: getLac()java.lang.Integer---android.net.ConnectivityManager: getActiveNetworkInfo()android.net.NetworkInfo : 0.0
android.location.Location: getTime()J---android.util.Log: e(java.lang.String,java.lang.String,java.lang.Throwable)java.lang.Integer : 0.0
android.util.Log: d(java.lang.String,java.lang.String)java.lang.Integer---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
android.telephony.TelephonyManager: getCellLocation()android.telephony.CellLocation---android.telephony.TelephonyManager: getNetworkOperator()java.lang.String : 0.0
